version: '3'
services:
  DB:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: DB
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - DB
    ports:
      - "5000:80"
    command: ["dotnet", "API-Inscription.dll"]

volumes:
  db_data: